title: Vitaliano Antonio Santoro  
logo: https://github.com/vitalianoas/portfolio/blob/main/WhatsApp%20Image%202024-09-13%20at%2017.52.27.jpeg
#description: text below image
show_downloads: false
theme: jekyll-theme-minimal
