title: Vitaliano Antonio Santoro  
logo: https://github.com/vitalianoas/portfolio/blob/main/myphoto.jpeg 
#description: Studente di statistica entusiasta ad entrare nel mondo dei dati.
show_downloads: false
theme: jekyll-theme-minimal
