title: Vitaliano Antonio Santoro  
image: https://github.com/vitalianoas/portfolio/blob/main/myphoto.jpeg 
description: Miei progetti: https://github.com/vitalianoas/Automatic-Data-Entry
show_downloads: false
theme: jekyll-theme-minimal
 
